// Life-moment definitions: detection signals and the content KBC shows.
// Each signal matches events in the customer's data. An event has a `source`
// (which maps to a consent category) and a `kind` (the category a bank's
// transaction-categorisation engine would assign).

export const CONSENT_CATEGORIES = {
  transactions: "Transactions",
  app: "In-app behaviour",
  customer_data: "Customer data",
  products: "Product info",
};

export const THRESHOLD = 0.45; // at or above: ask the customer; below: do nothing
export const WINDOW_YEARS = 2; // events from the last 2 simulated years count
export const SLOTS = ["Today 4pm", "Tomorrow 10:30am", "Fri 2pm"];

const BRANDS = {
  "De Lijn": ["Mobility", "Bus and tram pass for your commute", 30],
  "NMBS": ["Mobility", "Train season ticket for your commute", 40],
  "Donkey Republic": ["Mobility", "Shared bikes for short trips", 15],
  "Velo": ["Mobility", "City bikes in Antwerp", 15],
  "Q-Park": ["Mobility", "Parking through the app", 20],
  "Pronuptia": ["Wedding", "Wedding dresses", 80],
  "Jan Maes": ["Wedding", "Suits for the big day", 60],
  "TUI": ["Travel", "Book your honeymoon", 120],
  "Brussels Airport": ["Travel", "Parking and services at the airport", 50],
  "Smartphoto": ["Photos", "Photo books and cards", 25],
  "INNO": ["Shopping", "Wedding gift list", 50],
  "IKEA": ["Home", "Furnishing your new home", 70],
  "Colruyt": ["Groceries", "Earn Kate Coins on your groceries", 30],
  "Coolblue": ["Electronics", "Appliances for your new home", 60],
  "Brico": ["DIY", "DIY and renovation", 40],
  "HUBO": ["DIY", "DIY and garden", 40],
  "Gamma": ["DIY", "Building and renovation supplies", 40],
  "Telenet": ["Telecom", "Internet and TV at your new address", 60],
  "Dreambaby": ["Baby", "Baby essentials", 50],
  "Baby's Corner": ["Baby", "Nursery furniture", 50],
  "Dreamland": ["Toys", "Toys and games", 30],
  "Billit": ["Business", "E-invoicing for your business", 45],
  "Exact": ["Business", "Accounting software", 45],
  "Bruneau": ["Office", "Office supplies and furniture", 40],
  "Wonderbox": ["Gifts", "Experience gift boxes", 40],
};

const partner = (name, desc) => {
  const [category, def, coins] = BRANDS[name];
  return { name, category, description: desc || def, coins };
};
const tip = (name, description, url = null, action = null) => ({ name, description, url, action });
const NOTARIS = "https://www.notaris.be";
const sig = (source, kind, weight, text) => ({ source, kind, weight, text });

export const MOMENTS = [
  {
    id: "first_job", name: "First job", short: "First job",
    signals: [
      sig("transactions", "salary_first", 0.35, "First fixed salary"),
      sig("transactions", "employer_named", 0.20, "New employer named in the transfer description"),
      sig("transactions", "salary_jump", 0.15, "Salary much higher than before (student job)"),
      sig("transactions", "holiday_pay", 0.15, "First holiday pay and end-of-year bonus"),
    ],
    question: "Have you started your first job?",
    level: "Low: detection is fine", channel: "In-app", care: false,
    title: "Congrats on your first salary!",
    body: "A good moment to get your finances set up. Pick what suits you:",
    actions: ["Build a buffer: 3 months of fixed costs",
      "Holiday savings pot with an automatic transfer",
      "Start pension savings (tax benefit)",
      "Your first family liability insurance",
      "Check your hospitalisation insurance (through your employer or not)",
      "Budget overview"],
    timing: "The day after the salary arrives",
    partners: ["De Lijn", "NMBS", "Donkey Republic", "Velo", "Q-Park"].map(n => partner(n)),
    tips: [],
  },
  {
    id: "together", name: "Moving in / marriage", short: "Together",
    signals: [
      sig("transactions", "rent_shared", 0.35, "A second person contributes to the rent"),
      sig("transactions", "shared_costs", 0.25, "Shared fixed costs"),
      sig("transactions", "wedding_deposits", 0.25, "Deposits to a wedding venue, photographer, caterer and jeweller"),
    ],
    question: "Have you moved in together or are you getting married?",
    level: "Medium: let the customer say it", channel: "In-app", care: false,
    title: "Moving forward together, congrats!",
    body: "A few things that change now. We don't decide for you, we explain:",
    advisor: "Marital property regimes explained (joint or separate property), and an appointment with a notary",
    actions: ["A joint account, or not",
      "Combine your insurance: family liability, fire, car",
      "Your partner as beneficiary of your life insurance",
      "A savings pot for the wedding",
      "Travel insurance for the honeymoon"],
    timing: "Only after the customer confirms",
    partners: [partner("Pronuptia"), partner("Jan Maes"), partner("TUI"), partner("Brussels Airport"),
      partner("Smartphoto", "Wedding album and thank-you cards"), partner("INNO")],
    tips: [],
  },
  {
    id: "home", name: "Buying a home", short: "Home",
    signals: [
      sig("transactions", "savings_growth", 0.20, "Savings grow every month"),
      sig("app", "mortgage_simulator", 0.30, "Used the home plan and simulations in the app"),
      sig("transactions", "notary_deposit", 0.15, "Deposit paid to a notary"),
      sig("transactions", "contractor", 0.10, "Payments to a contractor or energy assessor"),
    ],
    question: "Are you planning to buy a home?",
    level: "Low to medium", channel: "In-app + advisor", care: false,
    title: "Ready to buy?",
    body: "You've been saving with a goal for a while. Here's how we can help:",
    advisor: "Mortgage simulation, discussed with your advisor",
    actions: ["Savings plan for your own contribution",
      "Mortgage protection insurance",
      "Fire insurance from the day of the deed",
      "Renovation loan and grants (energy, insulation)",
      "Moving checklist: change your address everywhere",
      "Your budget after the purchase"],
    timing: "On a weekday, when you open the simulator",
    partners: ["IKEA", "Colruyt", "Coolblue", "Brico", "HUBO", "Gamma", "Telenet"].map(n => partner(n)),
    tips: [tip("Notaris.be", "Buying a home: costs, the deed and finding a notary", NOTARIS)],
  },
  {
    id: "baby", name: "Baby", short: "Baby",
    signals: [
      sig("transactions", "baby_shop", 0.25, "Purchases at baby shops"),
      sig("transactions", "maternity", 0.30, "Payment to a hospital or maternity ward"),
      sig("transactions", "groeipakket", 0.40, "First Groeipakket payment (child benefit)"),
    ],
    question: "Has a little one arrived?",
    level: "Medium", channel: "In-app", care: false,
    title: "Welcome to your little one!",
    body: "For your child, in a few taps:",
    actions: ["Open an account in your child's name",
      "A monthly transfer (grandparents can contribute too)",
      "Add your child to your family liability and hospitalisation insurance",
      "Check the beneficiary of your life insurance",
      "Budget with the new fixed costs (childcare)",
      "Savings plan for their studies"],
    timing: "2 weeks after the birth, during the day",
    partners: [partner("Dreambaby"), partner("Baby's Corner"), partner("Dreamland"),
      partner("Smartphoto", "Birth announcement cards")],
    tips: [],
  },
  {
    id: "divorce", name: "Divorce", short: "Divorce",
    sensitive: true, openAsk: true, partnersOk: true, privateMessages: true,
    signals: [
      sig("transactions", "partner_stops_joint", 0.30, "Partner stops contributing to the joint account"),
      sig("transactions", "rental_deposit", 0.25, "Rental deposit paid for a second address"),
      sig("customer_data", "address_split", 0.20, "Change of address for one partner only"),
      sig("transactions", "lawyer", 0.20, "Payments to a lawyer or mediator"),
    ],
    level: "High: detect, but ask openly without naming it", channel: "Advisor", care: true,
    title: "Thank you for letting us know",
    body: "This is a hard time. We'll help you with the practical side, at your own pace:",
    advisor: "Your mortgage: who stays liable? Discuss it with your advisor",
    actions: ["Review access and powers of attorney",
      "Split the joint account",
      "Update the beneficiary of your life insurance",
      "Split your insurance policies",
      "Your children's accounts",
      "Maintenance payment as a standing order",
      "Rental deposit"],
    timing: "Only after the customer confirms",
    partners: [partner("IKEA", "Furnishing your own place"), partner("Coolblue", "Appliances for your own place"),
      partner("Brico"), partner("HUBO"), partner("Gamma"), partner("Colruyt")],
    tips: [tip("Advocaat.be", "Find a family-law lawyer near you", "https://www.advocaat.be"),
      tip("CAW", "Free, confidential support during a divorce", "https://www.caw.be"),
      tip("Notaris.be", "Dividing property and the family home", NOTARIS)],
  },
  {
    id: "job_loss", name: "Job loss", short: "Job loss",
    sensitive: true, openAsk: true,
    signals: [
      sig("transactions", "salary_missing", 0.40, "Salary no longer arrives"),
      sig("transactions", "severance", 0.30, "Large one-off deposit (severance pay)"),
      sig("transactions", "unemployment_benefit", 0.30, "First payment from a union or HVW (benefits fund)"),
    ],
    level: "High: gentle, no selling, ask openly", channel: "Advisor (on request)", care: true,
    balance: "€612.40",
    title: "We're here for you",
    body: "We noticed a change in your income. What might help now:",
    advisor: "Temporarily adjust your mortgage repayments, together with your advisor",
    actions: ["Overview of your fixed costs and subscriptions",
      "Set part of your severance pay aside for taxes",
      "Keep an eye on your buffer"],
    timing: "Within 24 hours, not in the evening",
    partners: [],
    tips: [tip("Your union", "Help with your dismissal, notice period and benefits"),
      tip("Convert your Kate Coins", "Turn your Kate Coins into euros on your account", null, "convert_coins"),
      tip("CAW", "Free support when things get tough", "https://www.caw.be")],
  },
  {
    id: "self_employed", name: "Self-employed", short: "Self-employed",
    signals: [
      sig("transactions", "multi_client_income", 0.30, "Income from several different clients"),
      sig("transactions", "social_fund", 0.25, "First payment to a social insurance fund"),
      sig("customer_data", "business_registration", 0.15, "Registration at a business desk"),
      sig("transactions", "vat_payment", 0.20, "VAT payments"),
      sig("transactions", "side_business", 0.10, "Salary and invoices side by side (side business)"),
    ],
    question: "Have you started your own business?",
    level: "Low", channel: "In-app", care: false,
    title: "Good luck with your own business!",
    body: "What starters often arrange too late:",
    actions: ["A separate business account",
      "Automatic pot for social contributions, VAT and taxes",
      "Supplementary pension for the self-employed (VAPZ)",
      "Guaranteed income insurance",
      "Professional liability insurance",
      "Link your accounting and e-invoicing",
      "Car lease"],
    timing: "After the first VAT payment",
    partners: [partner("Billit"), partner("Exact"), partner("Bruneau"), partner("Telenet", "Business internet")],
    tips: [tip("Unizo", "Advice and a network for starting entrepreneurs", "https://www.unizo.be"),
      tip("VLAIO", "Grants and support for your business in Flanders", "https://www.vlaio.be"),
      tip("Notaris.be", "Setting up a company with a notary", NOTARIS)],
  },
  {
    id: "large_sum", name: "Sudden large sum", short: "Large sum", careful: true,
    signals: [
      sig("transactions", "notary_inflow", 0.45, "Large deposit from a notary"),
      sig("transactions", "unusual_amount", 0.25, "Amount far larger than usual on this account"),
      sig("app", "viewed_investing", 0.10, "Viewed 'investing' in the app"),
    ],
    question: "Have you recently received a large sum?",
    level: "High: no rush, always a human", channel: "In-app + advisor", care: true,
    balance: "€187,431.20",
    title: "You received a large sum",
    body: "No rush. First park it safely, then choose calmly:",
    advisor: "Investment conversation based on your profile",
    actions: ["Park it safely first",
      "Upload the proof of origin right away",
      "The deposit guarantee explained: €100,000 per person per bank",
      "Compare early repayment of your mortgage",
      "Make full use of pension savings",
      "Donate to a charity (with a tax certificate)",
      "Fraud warning: never move money at someone else's request"],
    timing: "After 3 weeks, not right after the deposit",
    partners: [],
    tips: [],
  },
  {
    id: "retirement", name: "Retirement", short: "Retirement",
    signals: [
      sig("transactions", "pension_first", 0.40, "Last salary and first pension payment"),
      sig("transactions", "group_insurance", 0.30, "Large group insurance payout"),
      sig("transactions", "holiday_pay_pension", 0.15, "Different holiday pay"),
    ],
    question: "Have you retired?",
    level: "Medium: always with a human involved", channel: "In-app + advisor", care: false,
    title: "Welcome to your retirement",
    body: "Calmly, at your own pace:",
    advisor: "Investment conversation: where to put your supplementary pension",
    actions: ["Continue your employer's hospitalisation insurance individually",
      "Park your supplementary pension safely",
      "Gifting or estate planning with a notary",
      "Adapting your home",
      "Fraud protection",
      "Belmobiel: the bank comes to your home"],
    timing: "After the first pension payment",
    partners: [partner("Brussels Airport", "Parking and services for your trips"), partner("Wonderbox")],
    tips: [tip("Notaris.be", "Gifts and inheritance explained", NOTARIS)],
  },
];

export const MOMENTS_BY_ID = Object.fromEntries(MOMENTS.map(m => [m.id, m]));
export const MOMENT_IDS = new Set(MOMENTS.map(m => m.id));

// Options in the open question "Has something changed in your life?"
export const OPEN_ASK_OPTIONS = [{ id: "job_loss", label: "Job loss" }, { id: "divorce", label: "Divorce" }];

// Synthetic, clearly labelled figures for the scale dashboard.
export const STATS = {
  kpis: { customers_scanned: 2300000, moments_above_threshold: 11870, llm_share_pct: 0.5, deliberately_not_sent: 2430 },
  per_moment: [
    { label: "First job", value: 1840 }, { label: "Moving in / marriage", value: 2210 },
    { label: "Buying a home", value: 3120 }, { label: "Baby", value: 1290 },
    { label: "Self-employed", value: 640 }, { label: "Retirement", value: 2450 },
    { label: "Sudden large sum", value: 430, sensitive: true },
    { label: "Job loss", value: 860, sensitive: true },
    { label: "Divorce", value: 310, sensitive: true },
  ],
  funnel: [
    { label: "Candidate moments", value: 18400 }, { label: "Above threshold", value: 11870 },
    { label: "Asked the customer first", value: 4100 }, { label: "Deliberately not sent", value: 2430 },
  ],
  channels: [{ label: "In-app", value: 6400 }, { label: "Push notification", value: 3550 }, { label: "Advisor", value: 1920 }],
};
